name: Deploy CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
            luisluis12/calculadora:v1
            luisluis12/calculadora:latest
          
      - uses: actions/checkout@v1
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      
      - run: npm install
      - run: chmod +rwx ./node_modules/.bin/jest
      - run: npm test